name: ember_trip_view
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_map: ^8.0.0
  json_annotation: ^4.9.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  # assets:
    # - images/a_dot_burr.jpeg