name: ember_trip_view
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_map: ^8.0.0
  get_it: ^8.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  http: ^1.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  copy_with_extension_gen: ^6.0.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  mockito: ^5.4.5

flutter:
  uses-material-design: true